importScripts('https://unpkg.com/typograf@6.11.0/dist/typograf.js')
importScripts('https://cdnjs.cloudflare.com/ajax/libs/markdown-it/10.0.0/markdown-it.min.js')
importScripts('/latlng.js')

//inbox source
const SOURCE_ID = '614887b27e745e000978f53b'

const buttonLabel = new Map([
	['comment', 'Добавить'],
])
const colors = new Map([
	['comment', '#F25C63'],
])

setup(async () => {
	return {
		name: 'arf',
		version: '1.0.0',
		description: 'survey',
	}
})

on('install', async event => {
	overlay([
		['@', 'right-center', [
			['button', { icon: 'question', command: 'ShowHelp' }],
		]],
	])

	showHelp()
})

on('idle', async event => {
    // const uid = await getUserId()
    // if(!uid){
    //     console.log('User is not authorized: do not show buttons')
    //     return
    // }

	await toolbar([
		['AddComment', {
			label: buttonLabel.get('comment'),
			// icon: 'like',
			color: colors.get('comment'),
		}],
	], {
		foldedLabel: 'Добавить',
	})
})

function t(text) {
    const tp = new Typograf({ locale: ['ru', 'en-US'] })
    return tp.execute(text)
}

function mdToHtml(text) {
	const md = new markdownit()
	const raw = md.render(text)
	return t(raw)
}

function getFeaturePopupContent(feature) {
    const title = 'Идея'
	const kv = [
        ['project', 'Пара слов о проекте'],
        ['project_state', 'В какой стадии находится проект?'],
        ['mesto_about', 'какие задачи вы решите, применив mesto.io в своем проекте?'],
        ['mesto_requirements', 'Какой функционал / слои информации вам необходимы дополнительно?'],
	]
    .filter(([key, _]) => {
        const value = feature.properties[key]
        return !!value
    })
    .map(([key, label]) => {
        const value = feature.properties[key]
		return `<p><strong>${label}</strong><br/>${value}</p>`
	})

	return t([
		`<h2>${title}</h2>`,
		...kv,
	].join('\n\n'))
}

on('feature.select', async event => {
    const title = 'Идея'
	const featureId = event.data.featureId
	const layerId = event.data.layerId
	if (!featureId) {
		return
	}

	const fc = await requestFeatures([featureId])

	const feature = fc.features[0]
	const geometryType = feature.geometry.type
	assert(geometryType !== 'Point', new Error('Selected feature is not a point'))

	const html = getFeaturePopupContent(feature)
	if (!html) {
		return
	}

	await showMapPopup(feature.geometry.coordinates, ['html', {
        title, html, style: {
			padding: 8,
		}
	}])
})

command('AddComment', async ctx => {
	return AddFeature({
		title: 'Добавить',
	})
})

command("ShowHelp", () => {
	showHelp()
})

async function showHelp() {
	const html = mdToHtml(`
# архитекторы.рф

Это геоинформационная система mesto.io

Чтобы сервис жил и развивался, важно дополнять и наращивать его функционал, применяя mesto.io в разных проектах

Здесь можно отметить точку расположения вашего проекта на карте и пройти небольшой опрос о том, как вы видите применение и развитие mesto.io
    `)
	await showPopup([
		['html', { html }]
	], {
		title: 'Help',
		submit: 'Got it',
	})
}

async function AddFeature({ title }) {
	const mobile = await requestState('layout.mobile')
	const info = mobile
		? 'Добавьте точку на карте'
		: 'Добавьте точку на карте'
	const info2 = mobile
		? 'Наведите перекрестие и нажмите ОК'
		: 'Кликните по карте'
	const coord = await requestPoint(info2, info)

	const form = await requestInput([
		['city', ['select', {
			required: true,
			label: 'Город',
			mode: 'default-search',
		}, [
            ['option', {value: 'Абаза' }],
            ['option', {value: 'Абакан' }],
            ['option', {value: 'Абдулино' }],
            ['option', {value: 'Абинск' }],
            ['option', {value: 'Агидель' }],
            ['option', {value: 'Агрыз' }],
            ['option', {value: 'Адыгейск' }],
            ['option', {value: 'Азнакаево' }],
            ['option', {value: 'Азов' }],
            ['option', {value: 'Ак-Довурак' }],
            ['option', {value: 'Аксай' }],
            ['option', {value: 'Алагир' }],
            ['option', {value: 'Алапаевск' }],
            ['option', {value: 'Алатырь' }],
            ['option', {value: 'Алдан' }],
            ['option', {value: 'Алейск' }],
            ['option', {value: 'Александров' }],
            ['option', {value: 'Александровск' }],
            ['option', {value: 'Александровск-Сахалинский' }],
            ['option', {value: 'Алексеевка' }],
            ['option', {value: 'Алексин' }],
            ['option', {value: 'Алзамай' }],
            ['option', {value: 'Альметьевск' }],
            ['option', {value: 'Амурск' }],
            ['option', {value: 'Анадырь' }],
            ['option', {value: 'Анапа' }],
            ['option', {value: 'Ангарск' }],
            ['option', {value: 'Андреаполь' }],
            ['option', {value: 'Анжеро-Судженск' }],
            ['option', {value: 'Анива' }],
            ['option', {value: 'Апатиты' }],
            ['option', {value: 'Апрелевка' }],
            ['option', {value: 'Апшеронск' }],
            ['option', {value: 'Арамиль' }],
            ['option', {value: 'Аргун' }],
            ['option', {value: 'Ардатов' }],
            ['option', {value: 'Ардон' }],
            ['option', {value: 'Арзамас' }],
            ['option', {value: 'Аркадак' }],
            ['option', {value: 'Армавир' }],
            ['option', {value: 'Арсеньев' }],
            ['option', {value: 'Арск' }],
            ['option', {value: 'Артём' }],
            ['option', {value: 'Артёмовск' }],
            ['option', {value: 'Артёмовский' }],
            ['option', {value: 'Архангельск' }],
            ['option', {value: 'Асбест' }],
            ['option', {value: 'Асино' }],
            ['option', {value: 'Астрахань' }],
            ['option', {value: 'Аткарск' }],
            ['option', {value: 'Ахтубинск' }],
            ['option', {value: 'Ачинск' }],
            ['option', {value: 'Аша' }],
            ['option', {value: 'Бабаево' }],
            ['option', {value: 'Бабушкин' }],
            ['option', {value: 'Бавлы' }],
            ['option', {value: 'Багратионовск' }],
            ['option', {value: 'Байкальск' }],
            ['option', {value: 'Баймак' }],
            ['option', {value: 'Бакал' }],
            ['option', {value: 'Баксан' }],
            ['option', {value: 'Балабаново' }],
            ['option', {value: 'Балаково' }],
            ['option', {value: 'Балахна' }],
            ['option', {value: 'Балашиха' }],
            ['option', {value: 'Балашов' }],
            ['option', {value: 'Балей' }],
            ['option', {value: 'Балтийск' }],
            ['option', {value: 'Барабинск' }],
            ['option', {value: 'Барнаул' }],
            ['option', {value: 'Барыш' }],
            ['option', {value: 'Батайск' }],
            ['option', {value: 'Бежецк' }],
            ['option', {value: 'Белая Калитва' }],
            ['option', {value: 'Белая Холуница' }],
            ['option', {value: 'Белгород' }],
            ['option', {value: 'Белебей' }],
            ['option', {value: 'Белёв' }],
            ['option', {value: 'Белинский' }],
            ['option', {value: 'Белово' }],
            ['option', {value: 'Белогорск' }],
            ['option', {value: 'Белозерск' }],
            ['option', {value: 'Белокуриха' }],
            ['option', {value: 'Беломорск' }],
            ['option', {value: 'Белоозёрский' }],
            ['option', {value: 'Белорецк' }],
            ['option', {value: 'Белореченск' }],
            ['option', {value: 'Белоусово' }],
            ['option', {value: 'Белоярский' }],
            ['option', {value: 'Белый' }],
            ['option', {value: 'Бердск' }],
            ['option', {value: 'Березники' }],
            ['option', {value: 'Берёзовский' }],
            ['option', {value: 'Беслан' }],
            ['option', {value: 'Бийск' }],
            ['option', {value: 'Бикин' }],
            ['option', {value: 'Билибино' }],
            ['option', {value: 'Биробиджан' }],
            ['option', {value: 'Бирск' }],
            ['option', {value: 'Бирюсинск' }],
            ['option', {value: 'Бирюч' }],
            ['option', {value: 'Благовещенск' }],
            ['option', {value: 'Благодарный' }],
            ['option', {value: 'Бобров' }],
            ['option', {value: 'Богданович' }],
            ['option', {value: 'Богородицк' }],
            ['option', {value: 'Богородск' }],
            ['option', {value: 'Боготол' }],
            ['option', {value: 'Богучар' }],
            ['option', {value: 'Бодайбо' }],
            ['option', {value: 'Бокситогорск' }],
            ['option', {value: 'Болгар' }],
            ['option', {value: 'Бологое' }],
            ['option', {value: 'Болотное' }],
            ['option', {value: 'Болохово' }],
            ['option', {value: 'Болхов' }],
            ['option', {value: 'Большой Камень' }],
            ['option', {value: 'Бор' }],
            ['option', {value: 'Борзя' }],
            ['option', {value: 'Борисоглебск' }],
            ['option', {value: 'Боровичи' }],
            ['option', {value: 'Боровск' }],
            ['option', {value: 'Бородино' }],
            ['option', {value: 'Братск' }],
            ['option', {value: 'Бронницы' }],
            ['option', {value: 'Брянск' }],
            ['option', {value: 'Бугульма' }],
            ['option', {value: 'Бугуруслан' }],
            ['option', {value: 'Будённовск' }],
            ['option', {value: 'Бузулук' }],
            ['option', {value: 'Буинск' }],
            ['option', {value: 'Буй' }],
            ['option', {value: 'Буйнакск' }],
            ['option', {value: 'Бутурлиновка' }],
            ['option', {value: 'Валдай' }],
            ['option', {value: 'Валуйки' }],
            ['option', {value: 'Велиж' }],
            ['option', {value: 'Великие Луки' }],
            ['option', {value: 'Великий Новгород' }],
            ['option', {value: 'Великий Устюг' }],
            ['option', {value: 'Вельск' }],
            ['option', {value: 'Венёв' }],
            ['option', {value: 'Верещагино' }],
            ['option', {value: 'Верея' }],
            ['option', {value: 'Верхнеуральск' }],
            ['option', {value: 'Верхний Тагил' }],
            ['option', {value: 'Верхний Уфалей' }],
            ['option', {value: 'Верхняя Пышма' }],
            ['option', {value: 'Верхняя Салда' }],
            ['option', {value: 'Верхняя Тура' }],
            ['option', {value: 'Верхотурье' }],
            ['option', {value: 'Верхоянск' }],
            ['option', {value: 'Весьегонск' }],
            ['option', {value: 'Ветлуга' }],
            ['option', {value: 'Видное' }],
            ['option', {value: 'Вилюйск' }],
            ['option', {value: 'Вилючинск' }],
            ['option', {value: 'Вихоревка' }],
            ['option', {value: 'Вичуга' }],
            ['option', {value: 'Владивосток' }],
            ['option', {value: 'Владикавказ' }],
            ['option', {value: 'Владимир' }],
            ['option', {value: 'Волгоград' }],
            ['option', {value: 'Волгодонск' }],
            ['option', {value: 'Волгореченск' }],
            ['option', {value: 'Волжск' }],
            ['option', {value: 'Волжский' }],
            ['option', {value: 'Вологда' }],
            ['option', {value: 'Володарск' }],
            ['option', {value: 'Волоколамск' }],
            ['option', {value: 'Волосово' }],
            ['option', {value: 'Волхов' }],
            ['option', {value: 'Волчанск' }],
            ['option', {value: 'Вольск' }],
            ['option', {value: 'Воркута' }],
            ['option', {value: 'Воронеж' }],
            ['option', {value: 'Ворсма' }],
            ['option', {value: 'Воскресенск' }],
            ['option', {value: 'Воткинск' }],
            ['option', {value: 'Всеволожск' }],
            ['option', {value: 'Вуктыл' }],
            ['option', {value: 'Выборг' }],
            ['option', {value: 'Выкса' }],
            ['option', {value: 'Высоковск' }],
            ['option', {value: 'Высоцк' }],
            ['option', {value: 'Вытегра' }],
            ['option', {value: 'Вышний Волочёк' }],
            ['option', {value: 'Вяземский' }],
            ['option', {value: 'Вязники' }],
            ['option', {value: 'Вязьма' }],
            ['option', {value: 'Вятские Поляны' }],
            ['option', {value: 'Гаврилов Посад' }],
            ['option', {value: 'Гаврилов-Ям' }],
            ['option', {value: 'Гагарин' }],
            ['option', {value: 'Гаджиево' }],
            ['option', {value: 'Гай' }],
            ['option', {value: 'Галич' }],
            ['option', {value: 'Гатчина' }],
            ['option', {value: 'Гвардейск' }],
            ['option', {value: 'Гдов' }],
            ['option', {value: 'Геленджик' }],
            ['option', {value: 'Георгиевск' }],
            ['option', {value: 'Глазов' }],
            ['option', {value: 'Голицыно' }],
            ['option', {value: 'Горбатов' }],
            ['option', {value: 'Горно-Алтайск' }],
            ['option', {value: 'Горнозаводск' }],
            ['option', {value: 'Горняк' }],
            ['option', {value: 'Городец' }],
            ['option', {value: 'Городище' }],
            ['option', {value: 'Городовиковск' }],
            ['option', {value: 'Гороховец' }],
            ['option', {value: 'Горячий Ключ' }],
            ['option', {value: 'Грайворон' }],
            ['option', {value: 'Гремячинск' }],
            ['option', {value: 'Грозный' }],
            ['option', {value: 'Грязи' }],
            ['option', {value: 'Грязовец' }],
            ['option', {value: 'Губаха' }],
            ['option', {value: 'Губкин' }],
            ['option', {value: 'Губкинский' }],
            ['option', {value: 'Гудермес' }],
            ['option', {value: 'Гуково' }],
            ['option', {value: 'Гулькевичи' }],
            ['option', {value: 'Гурьевск' }],
            ['option', {value: 'Гусев' }],
            ['option', {value: 'Гусиноозёрск' }],
            ['option', {value: 'Гусь-Хрустальный' }],
            ['option', {value: 'Давлеканово' }],
            ['option', {value: 'Дагестанские Огни' }],
            ['option', {value: 'Далматово' }],
            ['option', {value: 'Дальнегорск' }],
            ['option', {value: 'Дальнереченск' }],
            ['option', {value: 'Данилов' }],
            ['option', {value: 'Данков' }],
            ['option', {value: 'Дегтярск' }],
            ['option', {value: 'Дедовск' }],
            ['option', {value: 'Демидов' }],
            ['option', {value: 'Дербент' }],
            ['option', {value: 'Десногорск' }],
            ['option', {value: 'Дзержинск' }],
            ['option', {value: 'Дзержинский' }],
            ['option', {value: 'Дивногорск' }],
            ['option', {value: 'Дигора' }],
            ['option', {value: 'Димитровград' }],
            ['option', {value: 'Дмитриев' }],
            ['option', {value: 'Дмитров' }],
            ['option', {value: 'Дмитровск' }],
            ['option', {value: 'Дно' }],
            ['option', {value: 'Добрянка' }],
            ['option', {value: 'Долгопрудный' }],
            ['option', {value: 'Долинск' }],
            ['option', {value: 'Домодедово' }],
            ['option', {value: 'Донецк' }],
            ['option', {value: 'Донской' }],
            ['option', {value: 'Дорогобуж' }],
            ['option', {value: 'Дрезна' }],
            ['option', {value: 'Дубна' }],
            ['option', {value: 'Дубовка' }],
            ['option', {value: 'Дудинка' }],
            ['option', {value: 'Духовщина' }],
            ['option', {value: 'Дюртюли' }],
            ['option', {value: 'Дятьково' }],
            ['option', {value: 'Егорьевск' }],
            ['option', {value: 'Ейск' }],
            ['option', {value: 'Екатеринбург' }],
            ['option', {value: 'Елабуга' }],
            ['option', {value: 'Елец' }],
            ['option', {value: 'Елизово' }],
            ['option', {value: 'Ельня' }],
            ['option', {value: 'Еманжелинск' }],
            ['option', {value: 'Емва' }],
            ['option', {value: 'Енисейск' }],
            ['option', {value: 'Ермолино' }],
            ['option', {value: 'Ершов' }],
            ['option', {value: 'Ессентуки' }],
            ['option', {value: 'Ефремов' }],
            ['option', {value: 'Железноводск' }],
            ['option', {value: 'Железногорск' }],
            ['option', {value: 'Железногорск-Илимский' }],
            ['option', {value: 'Жердевка' }],
            ['option', {value: 'Жигулёвск' }],
            ['option', {value: 'Жиздра' }],
            ['option', {value: 'Жирновск' }],
            ['option', {value: 'Жуков' }],
            ['option', {value: 'Жуковка' }],
            ['option', {value: 'Жуковский' }],
            ['option', {value: 'Завитинск' }],
            ['option', {value: 'Заводоуковск' }],
            ['option', {value: 'Заволжск' }],
            ['option', {value: 'Заволжье' }],
            ['option', {value: 'Задонск' }],
            ['option', {value: 'Заинск' }],
            ['option', {value: 'Закаменск' }],
            ['option', {value: 'Заозёрный' }],
            ['option', {value: 'Заозёрск' }],
            ['option', {value: 'Западная Двина' }],
            ['option', {value: 'Заполярный' }],
            ['option', {value: 'Зарайск' }],
            ['option', {value: 'Заречный' }],
            ['option', {value: 'Заринск' }],
            ['option', {value: 'Звенигово' }],
            ['option', {value: 'Звенигород' }],
            ['option', {value: 'Зверево' }],
            ['option', {value: 'Зеленогорск' }],
            ['option', {value: 'Зеленоградск' }],
            ['option', {value: 'Зеленодольск' }],
            ['option', {value: 'Зеленокумск' }],
            ['option', {value: 'Зерноград' }],
            ['option', {value: 'Зея' }],
            ['option', {value: 'Зима' }],
            ['option', {value: 'Златоуст' }],
            ['option', {value: 'Злынка' }],
            ['option', {value: 'Змеиногорск' }],
            ['option', {value: 'Знаменск' }],
            ['option', {value: 'Зубцов' }],
            ['option', {value: 'Зуевка' }],
            ['option', {value: 'Ивангород' }],
            ['option', {value: 'Иваново' }],
            ['option', {value: 'Ивантеевка' }],
            ['option', {value: 'Ивдель' }],
            ['option', {value: 'Игарка' }],
            ['option', {value: 'Ижевск' }],
            ['option', {value: 'Избербаш' }],
            ['option', {value: 'Изобильный' }],
            ['option', {value: 'Иланский' }],
            ['option', {value: 'Инза' }],
            ['option', {value: 'Иннополис' }],
            ['option', {value: 'Инсар' }],
            ['option', {value: 'Инта' }],
            ['option', {value: 'Ипатово' }],
            ['option', {value: 'Ирбит' }],
            ['option', {value: 'Иркутск' }],
            ['option', {value: 'Исилькуль' }],
            ['option', {value: 'Искитим' }],
            ['option', {value: 'Истра' }],
            ['option', {value: 'Ишим' }],
            ['option', {value: 'Ишимбай' }],
            ['option', {value: 'Йошкар-Ола' }],
            ['option', {value: 'Кадников' }],
            ['option', {value: 'Казань' }],
            ['option', {value: 'Калач' }],
            ['option', {value: 'Калач-на-Дону' }],
            ['option', {value: 'Калачинск' }],
            ['option', {value: 'Калининград' }],
            ['option', {value: 'Калининск' }],
            ['option', {value: 'Калтан' }],
            ['option', {value: 'Калуга' }],
            ['option', {value: 'Калязин' }],
            ['option', {value: 'Камбарка' }],
            ['option', {value: 'Каменка' }],
            ['option', {value: 'Каменногорск' }],
            ['option', {value: 'Каменск-Уральский' }],
            ['option', {value: 'Каменск-Шахтинский' }],
            ['option', {value: 'Камень-на-Оби' }],
            ['option', {value: 'Камешково' }],
            ['option', {value: 'Камызяк' }],
            ['option', {value: 'Камышин' }],
            ['option', {value: 'Камышлов' }],
            ['option', {value: 'Канаш' }],
            ['option', {value: 'Кандалакша' }],
            ['option', {value: 'Канск' }],
            ['option', {value: 'Карабаново' }],
            ['option', {value: 'Карабаш' }],
            ['option', {value: 'Карабулак' }],
            ['option', {value: 'Карасук' }],
            ['option', {value: 'Карачаевск' }],
            ['option', {value: 'Карачев' }],
            ['option', {value: 'Каргат' }],
            ['option', {value: 'Каргополь' }],
            ['option', {value: 'Карпинск' }],
            ['option', {value: 'Карталы' }],
            ['option', {value: 'Касимов' }],
            ['option', {value: 'Касли' }],
            ['option', {value: 'Каспийск' }],
            ['option', {value: 'Катав-Ивановск' }],
            ['option', {value: 'Катайск' }],
            ['option', {value: 'Качканар' }],
            ['option', {value: 'Кашин' }],
            ['option', {value: 'Кашира' }],
            ['option', {value: 'Кедровый' }],
            ['option', {value: 'Кемерово' }],
            ['option', {value: 'Кемь' }],
            ['option', {value: 'Кизел' }],
            ['option', {value: 'Кизилюрт' }],
            ['option', {value: 'Кизляр' }],
            ['option', {value: 'Кимовск' }],
            ['option', {value: 'Кимры' }],
            ['option', {value: 'Кингисепп' }],
            ['option', {value: 'Кинель' }],
            ['option', {value: 'Кинешма' }],
            ['option', {value: 'Киреевск' }],
            ['option', {value: 'Киренск' }],
            ['option', {value: 'Киржач' }],
            ['option', {value: 'Кириллов' }],
            ['option', {value: 'Кириши' }],
            ['option', {value: 'Киров' }],
            ['option', {value: 'Кировград' }],
            ['option', {value: 'Кирово-Чепецк' }],
            ['option', {value: 'Кировск' }],
            ['option', {value: 'Кирс' }],
            ['option', {value: 'Кирсанов' }],
            ['option', {value: 'Киселёвск' }],
            ['option', {value: 'Кисловодск' }],
            ['option', {value: 'Клин' }],
            ['option', {value: 'Клинцы' }],
            ['option', {value: 'Княгинино' }],
            ['option', {value: 'Ковдор' }],
            ['option', {value: 'Ковров' }],
            ['option', {value: 'Ковылкино' }],
            ['option', {value: 'Когалым' }],
            ['option', {value: 'Кодинск' }],
            ['option', {value: 'Козельск' }],
            ['option', {value: 'Козловка' }],
            ['option', {value: 'Козьмодемьянск' }],
            ['option', {value: 'Кола' }],
            ['option', {value: 'Кологрив' }],
            ['option', {value: 'Коломна' }],
            ['option', {value: 'Колпашево' }],
            ['option', {value: 'Кольчугино' }],
            ['option', {value: 'Коммунар' }],
            ['option', {value: 'Комсомольск' }],
            ['option', {value: 'Комсомольск-на-Амуре' }],
            ['option', {value: 'Конаково' }],
            ['option', {value: 'Кондопога' }],
            ['option', {value: 'Кондрово' }],
            ['option', {value: 'Константиновск' }],
            ['option', {value: 'Копейск' }],
            ['option', {value: 'Кораблино' }],
            ['option', {value: 'Кореновск' }],
            ['option', {value: 'Коркино' }],
            ['option', {value: 'Королёв' }],
            ['option', {value: 'Короча' }],
            ['option', {value: 'Корсаков' }],
            ['option', {value: 'Коряжма' }],
            ['option', {value: 'Костерёво' }],
            ['option', {value: 'Костомукша' }],
            ['option', {value: 'Кострома' }],
            ['option', {value: 'Котельники' }],
            ['option', {value: 'Котельниково' }],
            ['option', {value: 'Котельнич' }],
            ['option', {value: 'Котлас' }],
            ['option', {value: 'Котово' }],
            ['option', {value: 'Котовск' }],
            ['option', {value: 'Кохма' }],
            ['option', {value: 'Красавино' }],
            ['option', {value: 'Красноармейск' }],
            ['option', {value: 'Красновишерск' }],
            ['option', {value: 'Красногорск' }],
            ['option', {value: 'Краснодар' }],
            ['option', {value: 'Краснозаводск' }],
            ['option', {value: 'Краснознаменск' }],
            ['option', {value: 'Краснокаменск' }],
            ['option', {value: 'Краснокамск' }],
            ['option', {value: 'Краснослободск' }],
            ['option', {value: 'Краснотурьинск' }],
            ['option', {value: 'Красноуральск' }],
            ['option', {value: 'Красноуфимск' }],
            ['option', {value: 'Красноярск' }],
            ['option', {value: 'Красный Кут' }],
            ['option', {value: 'Красный Сулин' }],
            ['option', {value: 'Красный Холм' }],
            ['option', {value: 'Кремёнки' }],
            ['option', {value: 'Кропоткин' }],
            ['option', {value: 'Крымск' }],
            ['option', {value: 'Кстово' }],
            ['option', {value: 'Кубинка' }],
            ['option', {value: 'Кувандык' }],
            ['option', {value: 'Кувшиново' }],
            ['option', {value: 'Кудрово' }],
            ['option', {value: 'Кудымкар' }],
            ['option', {value: 'Кузнецк' }],
            ['option', {value: 'Куйбышев' }],
            ['option', {value: 'Кукмор' }],
            ['option', {value: 'Кулебаки' }],
            ['option', {value: 'Кумертау' }],
            ['option', {value: 'Кунгур' }],
            ['option', {value: 'Купино' }],
            ['option', {value: 'Курган' }],
            ['option', {value: 'Курганинск' }],
            ['option', {value: 'Курильск' }],
            ['option', {value: 'Курлово' }],
            ['option', {value: 'Куровское' }],
            ['option', {value: 'Курск' }],
            ['option', {value: 'Куртамыш' }],
            ['option', {value: 'Курчалой' }],
            ['option', {value: 'Курчатов' }],
            ['option', {value: 'Куса' }],
            ['option', {value: 'Кушва' }],
            ['option', {value: 'Кызыл' }],
            ['option', {value: 'Кыштым' }],
            ['option', {value: 'Кяхта' }],
            ['option', {value: 'Лабинск' }],
            ['option', {value: 'Лабытнанги' }],
            ['option', {value: 'Лагань' }],
            ['option', {value: 'Ладушкин' }],
            ['option', {value: 'Лаишево' }],
            ['option', {value: 'Лакинск' }],
            ['option', {value: 'Лангепас' }],
            ['option', {value: 'Лахденпохья' }],
            ['option', {value: 'Лебедянь' }],
            ['option', {value: 'Лениногорск' }],
            ['option', {value: 'Ленинск' }],
            ['option', {value: 'Ленинск-Кузнецкий' }],
            ['option', {value: 'Ленск' }],
            ['option', {value: 'Лермонтов' }],
            ['option', {value: 'Лесной' }],
            ['option', {value: 'Лесозаводск' }],
            ['option', {value: 'Лесосибирск' }],
            ['option', {value: 'Ливны' }],
            ['option', {value: 'Ликино-Дулёво' }],
            ['option', {value: 'Липецк' }],
            ['option', {value: 'Липки' }],
            ['option', {value: 'Лиски' }],
            ['option', {value: 'Лихославль' }],
            ['option', {value: 'Лобня' }],
            ['option', {value: 'Лодейное Поле' }],
            ['option', {value: 'Лосино-Петровский' }],
            ['option', {value: 'Луга' }],
            ['option', {value: 'Луза' }],
            ['option', {value: 'Лукоянов' }],
            ['option', {value: 'Луховицы' }],
            ['option', {value: 'Лысково' }],
            ['option', {value: 'Лысьва' }],
            ['option', {value: 'Лыткарино' }],
            ['option', {value: 'Льгов' }],
            ['option', {value: 'Любань' }],
            ['option', {value: 'Люберцы' }],
            ['option', {value: 'Любим' }],
            ['option', {value: 'Людиново' }],
            ['option', {value: 'Лянтор' }],
            ['option', {value: 'Магадан' }],
            ['option', {value: 'Магас' }],
            ['option', {value: 'Магнитогорск' }],
            ['option', {value: 'Майкоп' }],
            ['option', {value: 'Майский' }],
            ['option', {value: 'Макаров' }],
            ['option', {value: 'Макарьев' }],
            ['option', {value: 'Макушино' }],
            ['option', {value: 'Малая Вишера' }],
            ['option', {value: 'Малгобек' }],
            ['option', {value: 'Малмыж' }],
            ['option', {value: 'Малоархангельск' }],
            ['option', {value: 'Малоярославец' }],
            ['option', {value: 'Мамадыш' }],
            ['option', {value: 'Мамоново' }],
            ['option', {value: 'Мантурово' }],
            ['option', {value: 'Мариинск' }],
            ['option', {value: 'Мариинский Посад' }],
            ['option', {value: 'Маркс' }],
            ['option', {value: 'Махачкала' }],
            ['option', {value: 'Мглин' }],
            ['option', {value: 'Мегион' }],
            ['option', {value: 'Медвежьегорск' }],
            ['option', {value: 'Медногорск' }],
            ['option', {value: 'Медынь' }],
            ['option', {value: 'Межгорье' }],
            ['option', {value: 'Междуреченск' }],
            ['option', {value: 'Мезень' }],
            ['option', {value: 'Меленки' }],
            ['option', {value: 'Мелеуз' }],
            ['option', {value: 'Менделеевск' }],
            ['option', {value: 'Мензелинск' }],
            ['option', {value: 'Мещовск' }],
            ['option', {value: 'Миасс' }],
            ['option', {value: 'Микунь' }],
            ['option', {value: 'Миллерово' }],
            ['option', {value: 'Минеральные Воды' }],
            ['option', {value: 'Минусинск' }],
            ['option', {value: 'Миньяр' }],
            ['option', {value: 'Мирный' }],
            ['option', {value: 'Михайлов' }],
            ['option', {value: 'Михайловка' }],
            ['option', {value: 'Михайловск' }],
            ['option', {value: 'Мичуринск' }],
            ['option', {value: 'Могоча' }],
            ['option', {value: 'Можайск' }],
            ['option', {value: 'Можга' }],
            ['option', {value: 'Моздок' }],
            ['option', {value: 'Мончегорск' }],
            ['option', {value: 'Морозовск' }],
            ['option', {value: 'Моршанск' }],
            ['option', {value: 'Мосальск' }],
            ['option', {value: 'Москва' }],
            ['option', {value: 'Муравленко' }],
            ['option', {value: 'Мураши' }],
            ['option', {value: 'Мурино' }],
            ['option', {value: 'Мурманск' }],
            ['option', {value: 'Муром' }],
            ['option', {value: 'Мценск' }],
            ['option', {value: 'Мыски' }],
            ['option', {value: 'Мытищи' }],
            ['option', {value: 'Мышкин' }],
            ['option', {value: 'Набережные Челны' }],
            ['option', {value: 'Навашино' }],
            ['option', {value: 'Наволоки' }],
            ['option', {value: 'Надым' }],
            ['option', {value: 'Назарово' }],
            ['option', {value: 'Назрань' }],
            ['option', {value: 'Называевск' }],
            ['option', {value: 'Нальчик' }],
            ['option', {value: 'Нариманов' }],
            ['option', {value: 'Наро-Фоминск' }],
            ['option', {value: 'Нарткала' }],
            ['option', {value: 'Нарьян-Мар' }],
            ['option', {value: 'Находка' }],
            ['option', {value: 'Невель' }],
            ['option', {value: 'Невельск' }],
            ['option', {value: 'Невинномысск' }],
            ['option', {value: 'Невьянск' }],
            ['option', {value: 'Нелидово' }],
            ['option', {value: 'Неман' }],
            ['option', {value: 'Нерехта' }],
            ['option', {value: 'Нерчинск' }],
            ['option', {value: 'Нерюнгри' }],
            ['option', {value: 'Нестеров' }],
            ['option', {value: 'Нефтегорск' }],
            ['option', {value: 'Нефтекамск' }],
            ['option', {value: 'Нефтекумск' }],
            ['option', {value: 'Нефтеюганск' }],
            ['option', {value: 'Нея' }],
            ['option', {value: 'Нижневартовск' }],
            ['option', {value: 'Нижнекамск' }],
            ['option', {value: 'Нижнеудинск' }],
            ['option', {value: 'Нижние Серги' }],
            ['option', {value: 'Нижний Ломов' }],
            ['option', {value: 'Нижний Новгород' }],
            ['option', {value: 'Нижний Тагил' }],
            ['option', {value: 'Нижняя Салда' }],
            ['option', {value: 'Нижняя Тура' }],
            ['option', {value: 'Николаевск' }],
            ['option', {value: 'Николаевск-на-Амуре' }],
            ['option', {value: 'Никольск' }],
            ['option', {value: 'Никольское' }],
            ['option', {value: 'Новая Ладога' }],
            ['option', {value: 'Новая Ляля' }],
            ['option', {value: 'Новоалександровск' }],
            ['option', {value: 'Новоалтайск' }],
            ['option', {value: 'Новоаннинский' }],
            ['option', {value: 'Нововоронеж' }],
            ['option', {value: 'Новодвинск' }],
            ['option', {value: 'Новозыбков' }],
            ['option', {value: 'Новокубанск' }],
            ['option', {value: 'Новокузнецк' }],
            ['option', {value: 'Новокуйбышевск' }],
            ['option', {value: 'Новомичуринск' }],
            ['option', {value: 'Новомосковск' }],
            ['option', {value: 'Новопавловск' }],
            ['option', {value: 'Новоржев' }],
            ['option', {value: 'Новороссийск' }],
            ['option', {value: 'Новосибирск' }],
            ['option', {value: 'Новосиль' }],
            ['option', {value: 'Новосокольники' }],
            ['option', {value: 'Новотроицк' }],
            ['option', {value: 'Новоузенск' }],
            ['option', {value: 'Новоульяновск' }],
            ['option', {value: 'Новоуральск' }],
            ['option', {value: 'Новохопёрск' }],
            ['option', {value: 'Новочебоксарск' }],
            ['option', {value: 'Новочеркасск' }],
            ['option', {value: 'Новошахтинск' }],
            ['option', {value: 'Новый Оскол' }],
            ['option', {value: 'Новый Уренгой' }],
            ['option', {value: 'Ногинск' }],
            ['option', {value: 'Нолинск' }],
            ['option', {value: 'Норильск' }],
            ['option', {value: 'Ноябрьск' }],
            ['option', {value: 'Нурлат' }],
            ['option', {value: 'Нытва' }],
            ['option', {value: 'Нюрба' }],
            ['option', {value: 'Нягань' }],
            ['option', {value: 'Нязепетровск' }],
            ['option', {value: 'Няндома' }],
            ['option', {value: 'Облучье' }],
            ['option', {value: 'Обнинск' }],
            ['option', {value: 'Обоянь' }],
            ['option', {value: 'Обь' }],
            ['option', {value: 'Одинцово' }],
            ['option', {value: 'Озёрск' }],
            ['option', {value: 'Озёры' }],
            ['option', {value: 'Октябрьск' }],
            ['option', {value: 'Октябрьский' }],
            ['option', {value: 'Окуловка' }],
            ['option', {value: 'Олёкминск' }],
            ['option', {value: 'Оленегорск' }],
            ['option', {value: 'Олонец' }],
            ['option', {value: 'Омск' }],
            ['option', {value: 'Омутнинск' }],
            ['option', {value: 'Онега' }],
            ['option', {value: 'Опочка' }],
            ['option', {value: 'Орёл' }],
            ['option', {value: 'Оренбург' }],
            ['option', {value: 'Орехово-Зуево' }],
            ['option', {value: 'Орлов' }],
            ['option', {value: 'Орск' }],
            ['option', {value: 'Оса' }],
            ['option', {value: 'Осинники' }],
            ['option', {value: 'Осташков' }],
            ['option', {value: 'Остров' }],
            ['option', {value: 'Островной' }],
            ['option', {value: 'Острогожск' }],
            ['option', {value: 'Отрадное' }],
            ['option', {value: 'Отрадный' }],
            ['option', {value: 'Оха' }],
            ['option', {value: 'Оханск' }],
            ['option', {value: 'Очёр' }],
            ['option', {value: 'Павлово' }],
            ['option', {value: 'Павловск' }],
            ['option', {value: 'Павловский Посад' }],
            ['option', {value: 'Палласовка' }],
            ['option', {value: 'Партизанск' }],
            ['option', {value: 'Певек' }],
            ['option', {value: 'Пенза' }],
            ['option', {value: 'Первомайск' }],
            ['option', {value: 'Первоуральск' }],
            ['option', {value: 'Перевоз' }],
            ['option', {value: 'Пересвет' }],
            ['option', {value: 'Переславль-Залесский' }],
            ['option', {value: 'Пермь' }],
            ['option', {value: 'Пестово' }],
            ['option', {value: 'Петров Вал' }],
            ['option', {value: 'Петровск' }],
            ['option', {value: 'Петровск-Забайкальский' }],
            ['option', {value: 'Петрозаводск' }],
            ['option', {value: 'Петропавловск-Камчатский' }],
            ['option', {value: 'Петухово' }],
            ['option', {value: 'Петушки' }],
            ['option', {value: 'Печора' }],
            ['option', {value: 'Печоры' }],
            ['option', {value: 'Пикалёво' }],
            ['option', {value: 'Пионерский' }],
            ['option', {value: 'Питкяранта' }],
            ['option', {value: 'Плавск' }],
            ['option', {value: 'Пласт' }],
            ['option', {value: 'Плёс' }],
            ['option', {value: 'Поворино' }],
            ['option', {value: 'Подольск' }],
            ['option', {value: 'Подпорожье' }],
            ['option', {value: 'Покачи' }],
            ['option', {value: 'Покров' }],
            ['option', {value: 'Покровск' }],
            ['option', {value: 'Полевской' }],
            ['option', {value: 'Полесск' }],
            ['option', {value: 'Полысаево' }],
            ['option', {value: 'Полярные Зори' }],
            ['option', {value: 'Полярный' }],
            ['option', {value: 'Поронайск' }],
            ['option', {value: 'Порхов' }],
            ['option', {value: 'Похвистнево' }],
            ['option', {value: 'Почеп' }],
            ['option', {value: 'Починок' }],
            ['option', {value: 'Пошехонье' }],
            ['option', {value: 'Правдинск' }],
            ['option', {value: 'Приволжск' }],
            ['option', {value: 'Приморск' }],
            ['option', {value: 'Приморско-Ахтарск' }],
            ['option', {value: 'Приозерск' }],
            ['option', {value: 'Прокопьевск' }],
            ['option', {value: 'Пролетарск' }],
            ['option', {value: 'Протвино' }],
            ['option', {value: 'Прохладный' }],
            ['option', {value: 'Псков' }],
            ['option', {value: 'Пугачёв' }],
            ['option', {value: 'Пудож' }],
            ['option', {value: 'Пустошка' }],
            ['option', {value: 'Пучеж' }],
            ['option', {value: 'Пушкино' }],
            ['option', {value: 'Пущино' }],
            ['option', {value: 'Пыталово' }],
            ['option', {value: 'Пыть-Ях' }],
            ['option', {value: 'Пятигорск' }],
            ['option', {value: 'Радужный' }],
            ['option', {value: 'Райчихинск' }],
            ['option', {value: 'Раменское' }],
            ['option', {value: 'Рассказово' }],
            ['option', {value: 'Ревда' }],
            ['option', {value: 'Реж' }],
            ['option', {value: 'Реутов' }],
            ['option', {value: 'Ржев' }],
            ['option', {value: 'Родники' }],
            ['option', {value: 'Рославль' }],
            ['option', {value: 'Россошь' }],
            ['option', {value: 'Ростов-на-Дону' }],
            ['option', {value: 'Ростов' }],
            ['option', {value: 'Рошаль' }],
            ['option', {value: 'Ртищево' }],
            ['option', {value: 'Рубцовск' }],
            ['option', {value: 'Рудня' }],
            ['option', {value: 'Руза' }],
            ['option', {value: 'Рузаевка' }],
            ['option', {value: 'Рыбинск' }],
            ['option', {value: 'Рыбное' }],
            ['option', {value: 'Рыльск' }],
            ['option', {value: 'Ряжск' }],
            ['option', {value: 'Рязань' }],
            ['option', {value: 'Салават' }],
            ['option', {value: 'Салаир' }],
            ['option', {value: 'Салехард' }],
            ['option', {value: 'Сальск' }],
            ['option', {value: 'Самара' }],
            ['option', {value: 'Санкт-Петербург' }],
            ['option', {value: 'Саранск' }],
            ['option', {value: 'Сарапул' }],
            ['option', {value: 'Саратов' }],
            ['option', {value: 'Саров' }],
            ['option', {value: 'Сасово' }],
            ['option', {value: 'Сатка' }],
            ['option', {value: 'Сафоново' }],
            ['option', {value: 'Саяногорск' }],
            ['option', {value: 'Саянск' }],
            ['option', {value: 'Светлогорск' }],
            ['option', {value: 'Светлоград' }],
            ['option', {value: 'Светлый' }],
            ['option', {value: 'Светогорск' }],
            ['option', {value: 'Свирск' }],
            ['option', {value: 'Свободный' }],
            ['option', {value: 'Себеж' }],
            ['option', {value: 'Северо-Курильск' }],
            ['option', {value: 'Северобайкальск' }],
            ['option', {value: 'Северодвинск' }],
            ['option', {value: 'Североморск' }],
            ['option', {value: 'Североуральск' }],
            ['option', {value: 'Северск' }],
            ['option', {value: 'Севск' }],
            ['option', {value: 'Сегежа' }],
            ['option', {value: 'Сельцо' }],
            ['option', {value: 'Семёнов' }],
            ['option', {value: 'Семикаракорск' }],
            ['option', {value: 'Семилуки' }],
            ['option', {value: 'Сенгилей' }],
            ['option', {value: 'Серафимович' }],
            ['option', {value: 'Сергач' }],
            ['option', {value: 'Сергиев Посад' }],
            ['option', {value: 'Сердобск' }],
            ['option', {value: 'Серов' }],
            ['option', {value: 'Серпухов' }],
            ['option', {value: 'Сертолово' }],
            ['option', {value: 'Сибай' }],
            ['option', {value: 'Сим' }],
            ['option', {value: 'Сковородино' }],
            ['option', {value: 'Скопин' }],
            ['option', {value: 'Славгород' }],
            ['option', {value: 'Славск' }],
            ['option', {value: 'Славянск-на-Кубани' }],
            ['option', {value: 'Сланцы' }],
            ['option', {value: 'Слободской' }],
            ['option', {value: 'Слюдянка' }],
            ['option', {value: 'Смоленск' }],
            ['option', {value: 'Снежинск' }],
            ['option', {value: 'Снежногорск' }],
            ['option', {value: 'Собинка' }],
            ['option', {value: 'Советск' }],
            ['option', {value: 'Советская Гавань' }],
            ['option', {value: 'Советский' }],
            ['option', {value: 'Сокол' }],
            ['option', {value: 'Солигалич' }],
            ['option', {value: 'Соликамск' }],
            ['option', {value: 'Солнечногорск' }],
            ['option', {value: 'Соль-Илецк' }],
            ['option', {value: 'Сольвычегодск' }],
            ['option', {value: 'Сольцы' }],
            ['option', {value: 'Сорочинск' }],
            ['option', {value: 'Сорск' }],
            ['option', {value: 'Сортавала' }],
            ['option', {value: 'Сосенский' }],
            ['option', {value: 'Сосновка' }],
            ['option', {value: 'Сосновоборск' }],
            ['option', {value: 'Сосновый Бор' }],
            ['option', {value: 'Сосногорск' }],
            ['option', {value: 'Сочи' }],
            ['option', {value: 'Спас-Деменск' }],
            ['option', {value: 'Спас-Клепики' }],
            ['option', {value: 'Спасск' }],
            ['option', {value: 'Спасск-Дальний' }],
            ['option', {value: 'Спасск-Рязанский' }],
            ['option', {value: 'Среднеколымск' }],
            ['option', {value: 'Среднеуральск' }],
            ['option', {value: 'Сретенск' }],
            ['option', {value: 'Ставрополь' }],
            ['option', {value: 'Старая Купавна' }],
            ['option', {value: 'Старая Русса' }],
            ['option', {value: 'Старица' }],
            ['option', {value: 'Стародуб' }],
            ['option', {value: 'Старый Оскол' }],
            ['option', {value: 'Стерлитамак' }],
            ['option', {value: 'Стрежевой' }],
            ['option', {value: 'Строитель' }],
            ['option', {value: 'Струнино' }],
            ['option', {value: 'Ступино' }],
            ['option', {value: 'Суворов' }],
            ['option', {value: 'Суджа' }],
            ['option', {value: 'Судогда' }],
            ['option', {value: 'Суздаль' }],
            ['option', {value: 'Сунжа' }],
            ['option', {value: 'Суоярви' }],
            ['option', {value: 'Сураж' }],
            ['option', {value: 'Сургут' }],
            ['option', {value: 'Суровикино' }],
            ['option', {value: 'Сурск' }],
            ['option', {value: 'Сусуман' }],
            ['option', {value: 'Сухиничи' }],
            ['option', {value: 'Сухой Лог' }],
            ['option', {value: 'Сызрань' }],
            ['option', {value: 'Сыктывкар' }],
            ['option', {value: 'Сысерть' }],
            ['option', {value: 'Сычёвка' }],
            ['option', {value: 'Сясьстрой' }],
            ['option', {value: 'Тавда' }],
            ['option', {value: 'Таганрог' }],
            ['option', {value: 'Тайга' }],
            ['option', {value: 'Тайшет' }],
            ['option', {value: 'Талдом' }],
            ['option', {value: 'Талица' }],
            ['option', {value: 'Тамбов' }],
            ['option', {value: 'Тара' }],
            ['option', {value: 'Тарко-Сале' }],
            ['option', {value: 'Таруса' }],
            ['option', {value: 'Татарск' }],
            ['option', {value: 'Таштагол' }],
            ['option', {value: 'Тверь' }],
            ['option', {value: 'Теберда' }],
            ['option', {value: 'Тейково' }],
            ['option', {value: 'Темников' }],
            ['option', {value: 'Темрюк' }],
            ['option', {value: 'Терек' }],
            ['option', {value: 'Тетюши' }],
            ['option', {value: 'Тимашёвск' }],
            ['option', {value: 'Тихвин' }],
            ['option', {value: 'Тихорецк' }],
            ['option', {value: 'Тобольск' }],
            ['option', {value: 'Тогучин' }],
            ['option', {value: 'Тольятти' }],
            ['option', {value: 'Томари' }],
            ['option', {value: 'Томмот' }],
            ['option', {value: 'Томск' }],
            ['option', {value: 'Топки' }],
            ['option', {value: 'Торжок' }],
            ['option', {value: 'Торопец' }],
            ['option', {value: 'Тосно' }],
            ['option', {value: 'Тотьма' }],
            ['option', {value: 'Трёхгорный' }],
            ['option', {value: 'Троицк' }],
            ['option', {value: 'Трубчевск' }],
            ['option', {value: 'Туапсе' }],
            ['option', {value: 'Туймазы' }],
            ['option', {value: 'Тула' }],
            ['option', {value: 'Тулун' }],
            ['option', {value: 'Туран' }],
            ['option', {value: 'Туринск' }],
            ['option', {value: 'Тутаев' }],
            ['option', {value: 'Тында' }],
            ['option', {value: 'Тырныауз' }],
            ['option', {value: 'Тюкалинск' }],
            ['option', {value: 'Тюмень' }],
            ['option', {value: 'Уварово' }],
            ['option', {value: 'Углегорск' }],
            ['option', {value: 'Углич' }],
            ['option', {value: 'Удачный' }],
            ['option', {value: 'Удомля' }],
            ['option', {value: 'Ужур' }],
            ['option', {value: 'Узловая' }],
            ['option', {value: 'Улан-Удэ' }],
            ['option', {value: 'Ульяновск' }],
            ['option', {value: 'Унеча' }],
            ['option', {value: 'Урай' }],
            ['option', {value: 'Урень' }],
            ['option', {value: 'Уржум' }],
            ['option', {value: 'Урус-Мартан' }],
            ['option', {value: 'Урюпинск' }],
            ['option', {value: 'Усинск' }],
            ['option', {value: 'Усмань' }],
            ['option', {value: 'Усолье-Сибирское' }],
            ['option', {value: 'Усолье' }],
            ['option', {value: 'Уссурийск' }],
            ['option', {value: 'Усть-Джегута' }],
            ['option', {value: 'Усть-Илимск' }],
            ['option', {value: 'Усть-Катав' }],
            ['option', {value: 'Усть-Кут' }],
            ['option', {value: 'Усть-Лабинск' }],
            ['option', {value: 'Устюжна' }],
            ['option', {value: 'Уфа' }],
            ['option', {value: 'Ухта' }],
            ['option', {value: 'Учалы' }],
            ['option', {value: 'Уяр' }],
            ['option', {value: 'Фатеж' }],
            ['option', {value: 'Фокино' }],
            ['option', {value: 'Фролово' }],
            ['option', {value: 'Фрязино' }],
            ['option', {value: 'Фурманов' }],
            ['option', {value: 'Хабаровск' }],
            ['option', {value: 'Хадыженск' }],
            ['option', {value: 'Ханты-Мансийск' }],
            ['option', {value: 'Харабали' }],
            ['option', {value: 'Харовск' }],
            ['option', {value: 'Хасавюрт' }],
            ['option', {value: 'Хвалынск' }],
            ['option', {value: 'Хилок' }],
            ['option', {value: 'Химки' }],
            ['option', {value: 'Холм' }],
            ['option', {value: 'Холмск' }],
            ['option', {value: 'Хотьково' }],
            ['option', {value: 'Цивильск' }],
            ['option', {value: 'Цимлянск' }],
            ['option', {value: 'Циолковский' }],
            ['option', {value: 'Чадан' }],
            ['option', {value: 'Чайковский' }],
            ['option', {value: 'Чапаевск' }],
            ['option', {value: 'Чаплыгин' }],
            ['option', {value: 'Чебаркуль' }],
            ['option', {value: 'Чебоксары' }],
            ['option', {value: 'Чегем' }],
            ['option', {value: 'Чекалин' }],
            ['option', {value: 'Челябинск' }],
            ['option', {value: 'Чердынь' }],
            ['option', {value: 'Черемхово' }],
            ['option', {value: 'Черепаново' }],
            ['option', {value: 'Череповец' }],
            ['option', {value: 'Черкесск' }],
            ['option', {value: 'Чёрмоз' }],
            ['option', {value: 'Черноголовка' }],
            ['option', {value: 'Черногорск' }],
            ['option', {value: 'Чернушка' }],
            ['option', {value: 'Черняховск' }],
            ['option', {value: 'Чехов' }],
            ['option', {value: 'Чистополь' }],
            ['option', {value: 'Чита' }],
            ['option', {value: 'Чкаловск' }],
            ['option', {value: 'Чудово' }],
            ['option', {value: 'Чулым' }],
            ['option', {value: 'Чусовой' }],
            ['option', {value: 'Чухлома' }],
            ['option', {value: 'Шагонар' }],
            ['option', {value: 'Шадринск' }],
            ['option', {value: 'Шали' }],
            ['option', {value: 'Шарыпово' }],
            ['option', {value: 'Шарья' }],
            ['option', {value: 'Шатура' }],
            ['option', {value: 'Шахты' }],
            ['option', {value: 'Шахунья' }],
            ['option', {value: 'Шацк' }],
            ['option', {value: 'Шебекино' }],
            ['option', {value: 'Шелехов' }],
            ['option', {value: 'Шенкурск' }],
            ['option', {value: 'Шилка' }],
            ['option', {value: 'Шимановск' }],
            ['option', {value: 'Шиханы' }],
            ['option', {value: 'Шлиссельбург' }],
            ['option', {value: 'Шумерля' }],
            ['option', {value: 'Шумиха' }],
            ['option', {value: 'Шуя' }],
            ['option', {value: 'Щёкино' }],
            ['option', {value: 'Щёлково' }],
            ['option', {value: 'Щигры' }],
            ['option', {value: 'Щучье' }],
            ['option', {value: 'Электрогорск' }],
            ['option', {value: 'Электросталь' }],
            ['option', {value: 'Электроугли' }],
            ['option', {value: 'Элиста' }],
            ['option', {value: 'Энгельс' }],
            ['option', {value: 'Эртиль' }],
            ['option', {value: 'Югорск' }],
            ['option', {value: 'Южа' }],
            ['option', {value: 'Южно-Сахалинск' }],
            ['option', {value: 'Южно-Сухокумск' }],
            ['option', {value: 'Южноуральск' }],
            ['option', {value: 'Юрга' }],
            ['option', {value: 'Юрьев-Польский' }],
            ['option', {value: 'Юрьевец' }],
            ['option', {value: 'Юрюзань' }],
            ['option', {value: 'Юхнов' }],
            ['option', {value: 'Ядрин' }],
            ['option', {value: 'Якутск' }],
            ['option', {value: 'Ялуторовск' }],
            ['option', {value: 'Янаул' }],
            ['option', {value: 'Яранск' }],
            ['option', {value: 'Яровое' }],
            ['option', {value: 'Ярославль' }],
            ['option', {value: 'Ярцево' }],
            ['option', {value: 'Ясногорск' }],
            ['option', {value: 'Ясный' }],
            ['option', {value: 'Яхрома' }],
        ]
		]],
		// ['photos', ['image', {
		// 	required: false,
		// 	label: 'Фотографии',
		// 	multiple: true,
		// }]],
		['project', ['text', {
			required: true,
			label: 'Пара слов о проекте',
			rows: 3,
		}]],
        ['project_state', ['input', {
            required: false,
            label: 'В какой стадии находится проект?',
            placeholder: 'идея / в процессе / уже все сделали',
        }]],

        //4
        ['mesto_about', ['text', {
            required: true,
            label: 'какие задачи вы решите, применив mesto.io в своем проекте?',
            rows: 3,
        }]],

        // 5
        ['mesto_requirements', ['text', {
            required: false,
            label: 'Какой функционал / слои информации вам необходимы дополнительно?',
            rows: 3,
        }]],
        
        // ['project_state', ['select', {
        //     required: false,
        //     label: 'В какой стадии находится проект?',
        //     mode: 'single',
        // }, [
        //         ['option', { value: 'идея' }],
        //         ['option', { value: 'в работе' }],
        //         ['option', { value: 'уже все сделали' }],
        //     ],
        // ]],
        ['contact_name', ['input', {
            required: true,
            label: 'Имя',
            // placeholder: '',
        }]],
        ['contact', ['input', {
            required: true,
            label: 'Имя',
            label: 'Контакты',
            placeholder: 'телефон, e-mail или телеграмм',
            // pattern: {
            //        value: /^([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4})?$/i,
            //        message: "invalid email address"
            //    }
        }]],
	], {
		title,
		submit: 'Добавить',
		cancel: 'Отмена',
	})

    console.log('input:', form)

	const properties = {
		city: form.city,
		project: form.project,
        project_state: form.project_state,
		mesto_about: form.mesto_about,
		mesto_requirements: form.mesto_requirements,
		contact: form.contact,
		contact_name: form.contact_name,
	}

    const user = await getUser()
    if(user) {
        properties.user = user.name
        properties.uid = user.id
    }

    const date = new Date()
    properties.dateAdded = date.toString()

	const f = {
		type: 'FeatureCollection',
		features: [
			{
				type: 'Feature',
				geometry: {
					type: 'Point',
					coordinates: [coord.lng, coord.lat]
				},
				properties,
			}
		]
	}

	await addFeatures(f, {
		sourceId: SOURCE_ID,
	})
}
